# Generated on Tues Mar 9 10:42:08 2021
# Modified on mc-mit-ctrl-user-parameters.yaml
# Author: Yinuo Wang
__collection-name__: user-parameters

# This collection contains user parameters for the IUST robot.

# For IUST robot
use_wbc           : 0                   # Flag to indicate whether to use WBIC or not
Kp_ori            : [100, 100, 100]     # Proportional gains for the orientation controller
Kd_ori            : [15, 20, 20]        # Derivative gains for the orientation controller
Kp_body           : [100, 100, 100]     # Proportional gains for the body controller
Kd_body           : [15, 15, 15]        # Derivative gains for the body controller
Kp_foot           : [500, 500, 500]     # Proportional gains for the foot controller
Kd_foot           : [20, 20, 20]        # Derivative gains for the foot controller
Kp_joint          : [5, 5, 5]           # Proportional gains for the joint controller
Kd_joint          : [1, 1, 1]           # Derivative gains for the joint controller

# For Mini-Cheetah
#Kp_body           : [100, 100, 100]
#Kd_body           : [10, 10, 10]
#Kp_foot           : [500, 500, 500]
#Kd_foot           : [10, 10, 10]
#Kp_ori            : [100, 100, 100]
#Kd_ori            : [10, 10, 10]
#Kd_joint          : [1, 0.2, 0.2]
#Kp_joint          : [3, 3, 3]

# cMPC
cmpc_gait         : 9                   # Gait type for cMPC
Q_pos             : [1, 1, 50]          # Position cost matrix for cMPC
Q_vel             : [1, 1, 1]           # Velocity cost matrix for cMPC
Q_ori             : [0, 0, 1]           # Orientation cost matrix for cMPC
Q_ang             : [1, 1, 1]           # Angular cost matrix for cMPC
R                 : 1e-05               # Control cost matrix for cMPC
cmpc_x_drag       : 3                   # Drag coefficient for cMPC
cmpc_use_sparse   : 0                   # Flag to indicate whether to use sparse matrix for cMPC or not
cmpc_bonus_swing  : 0                   # Flag to indicate whether to use bonus swing for cMPC or not
jcqp_alpha        : 1.5                 # Alpha parameter for JCQP
jcqp_max_iter     : 10000               # Maximum iteration for JCQP
jcqp_rho          : 1e-07               # Rho parameter for JCQP
jcqp_sigma        : 1e-08               # Sigma parameter for JCQP
jcqp_terminate    : 0.1                 # Termination parameter for JCQP
use_jcqp          : 0                   # Flag to indicate whether to use JCQP or not

# Swing leg parameters
Swing_Kp_cartesian : [700, 700, 700]    # Proportional gains for the swing leg cartesian controller
Swing_Kd_cartesian : [14, 14, 14]       # Derivative gains for the swing leg cartesian controller
Swing_Kp_joint     : [0, 0, 0]          # Proportional gains for the swing leg joint controller
Swing_Kd_joint     : [1, 1, 1]          # Derivative gains for the swing leg joint controller
Swing_step_offset  : [0, 0.05, -0.003]  # Step offset for the swing leg controller
Swing_traj_height  : 0.05               # Trajectory height for the swing leg controller
Swing_use_tau_ff   : 0                  # Flag to indicate whether to use feedforward torque for the swing leg controller or not

# Gait parameters
gait_type             : 4               # Gait type for the robot
gait_period_time      : 0.5             # Period time for the gait
gait_switching_phase  : 0.5             # Switching phase for the gait
gait_override         : 4               # Override for the gait
gait_max_leg_angle    : 15              # Maximum leg angle for the gait
gait_max_stance_time  : 0.25            # Maximum stance time for the gait
gait_min_stance_time  : 0.1             # Minimum stance time for the gait
